name: web-proxy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm install -g npm@latest

      - name: Install Dependencies & Build Proxy
        run: npm install && npm run build:cf-workers:webpack

      - name: Deploy Proxy
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_KEY }}
          workingDirectory: .cf-workers
